name: test file

on:
  pull_request:
  push:
    branches:
      - devel

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        ros_distribution:
          -foxy
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.2
    #with:
  #      required-ros-distributions: ${{ matrix.ros_distribution }}
    
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: ros2labview_examples
        target-ros2-distro: foxy

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
